### ISSUE TITLE
Does not download Stable correctly if vscode-test has not been run separately.

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-extension-test-runner#13]
When clicking the "run test" button, if vscode has to be downloaded, it fails with `invalid package node_modules.asar`. If you run `vscode-test` outside of the test runner (e.g. at the terminal), it will install as expected.

```
 >  vscode-test --label 0 --reporter D:\vscode-pester\node_modules\.pnpm\@vscode+test-cli@0.0.4\node_modules\@vscode\test-cli\out\fullJsonStreamReporter.cjs --run c:\Users\JGrote\Projects\vscode-pester\test\test.ts
Downloading VS Code 1.85.1 from https://update.code.visualstudio.com/1.85.1/win32-x64-archive/stable
Downloading VS Code (131526249B)
Downloading VS Code [==============================] 100%Error downloading, retrying (attempt 1 of 3): Invalid package c:\Users\JGrote\Projects\vscode-pester\.vscode-test\vscode-win32-x64-archive-1.85.1\resources\app\node_modules.asar
Downloading VS Code 1.85.1 from https://update.code.visualstudio.com/1.85.1/win32-x64-archive/stable
Downloading VS Code (131526249B)
Downloading VS Code [==============================] 100%Error downloading, retrying (attempt 3 of 3): Invalid package c:\Users\JGrote\Projects\vscode-pester\.vscode-test\vscode-win32-x64-archive-1.85.1\resources\app\node_modules.asar
Downloading VS Code 1.85.1 from https://update.code.visualstudio.com/1.85.1/win32-x64-archive/stable
Downloading VS Code (131526249B)
Error: Invalid package c:\Users\JGrote\Projects\vscode-pester\.vscode-test\vscode-win32-x64-archive-1.85.1\resources\app\node_modules.asar
    at createError (node:electron/js2c/asar_bundle:2:1608)
    at t.<computed> [as open] (node:electron/js2c/asar_bundle:2:2442)
    at WriteStream._construct (node:internal/fs/streams:69:17)
    at constructNT (node:internal/streams/destroy:275:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Error: Failed to download and unzip VS Code 1.85.1
    at download (D:\vscode-pester\node_modules\.pnpm\@vscode+test-electron@2.3.8\node_modules\@vscode\test-electron\out\download.js:369:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadAndUnzipVSCode (D:\vscode-pester\node_modules\.pnpm\@vscode+test-electron@2.3.8\node_modules\@vscode\test-electron\out\download.js:383:12)
    at async Module.runTests (D:\vscode-pester\node_modules\.pnpm\@vscode+test-electron@2.3.8\node_modules\@vscode\test-electron\out\runTest.js:19:40)
    at async runConfigs (file:///D:/vscode-pester/node_modules/.pnpm/@vscode+test-cli@0.0.4/node_modules/@vscode/test-cli/out/bin.mjs:339:30)
    at async main (file:///D:/vscode-pester/node_modules/.pnpm/@vscode+test-cli@0.0.4/node_modules/@vscode/test-cli/out/bin.mjs:226:20)
Downloading VS Code [==============================] 100%
Error: Test process exited with code 1
```

**Comment by JustinGrote** [comment]
Related to #9 but this should be resolved in the test runner rather than just worked around.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-test/commit/6d096d4ff63489fb51d877d2d65151d5a1918119
